/** @format */

export interface Country {
  name: string;
  code: string;
  phone_code: string;
  flag: string;
}

export const COUNTRIES: Record<string, Country> = {
  AF: { name: 'Afghanistan', code: 'AF', phone_code: '+93', flag: '🇦🇫' },
  AL: { name: 'Albania', code: 'AL', phone_code: '+355', flag: '🇦🇱' },
  DZ: { name: 'Algeria', code: 'DZ', phone_code: '+213', flag: '🇩🇿' },
  AS: { name: 'American Samoa', code: 'AS', phone_code: '+1-684', flag: '🇦🇸' },
  AD: { name: 'Andorra', code: 'AD', phone_code: '+376', flag: '🇦🇩' },
  AO: { name: 'Angola', code: 'AO', phone_code: '+244', flag: '🇦🇴' },
  AI: { name: 'Anguilla', code: 'AI', phone_code: '+1-264', flag: '🇦🇮' },
  AQ: { name: 'Antarctica', code: 'AQ', phone_code: '+672', flag: '🇦🇶' },
  AG: {
    name: 'Antigua and Barbuda',
    code: 'AG',
    phone_code: '+1-268',
    flag: '🇦🇬',
  },
  AR: { name: 'Argentina', code: 'AR', phone_code: '+54', flag: '🇦🇷' },
  AM: { name: 'Armenia', code: 'AM', phone_code: '+374', flag: '🇦🇲' },
  AW: { name: 'Aruba', code: 'AW', phone_code: '+297', flag: '🇦🇼' },
  AU: { name: 'Australia', code: 'AU', phone_code: '+61', flag: '🇦🇺' },
  AT: { name: 'Austria', code: 'AT', phone_code: '+43', flag: '🇦🇹' },
  AZ: { name: 'Azerbaijan', code: 'AZ', phone_code: '+994', flag: '🇦🇿' },
  BS: { name: 'Bahamas', code: 'BS', phone_code: '+1-242', flag: '🇧🇸' },
  BH: { name: 'Bahrain', code: 'BH', phone_code: '+973', flag: '🇧🇭' },
  BD: { name: 'Bangladesh', code: 'BD', phone_code: '+880', flag: '🇧🇩' },
  BB: { name: 'Barbados', code: 'BB', phone_code: '+1-246', flag: '🇧🇧' },
  BY: { name: 'Belarus', code: 'BY', phone_code: '+375', flag: '🇧🇾' },
  BE: { name: 'Belgium', code: 'BE', phone_code: '+32', flag: '🇧🇪' },
  BZ: { name: 'Belize', code: 'BZ', phone_code: '+501', flag: '🇧🇿' },
  BJ: { name: 'Benin', code: 'BJ', phone_code: '+229', flag: '🇧🇯' },
  BM: { name: 'Bermuda', code: 'BM', phone_code: '+1-441', flag: '🇧🇲' },
  BT: { name: 'Bhutan', code: 'BT', phone_code: '+975', flag: '🇧🇹' },
  BO: { name: 'Bolivia', code: 'BO', phone_code: '+591', flag: '🇧🇴' },
  BA: {
    name: 'Bosnia and Herzegovina',
    code: 'BA',
    phone_code: '+387',
    flag: '🇧🇦',
  },
  BW: { name: 'Botswana', code: 'BW', phone_code: '+267', flag: '🇧🇼' },
  BR: { name: 'Brazil', code: 'BR', phone_code: '+55', flag: '🇧🇷' },
  IO: {
    name: 'British Indian Ocean Territory',
    code: 'IO',
    phone_code: '+246',
    flag: '🇮🇴',
  },
  VG: {
    name: 'British Virgin Islands',
    code: 'VG',
    phone_code: '+1-284',
    flag: '🇻🇬',
  },
  BN: { name: 'Brunei', code: 'BN', phone_code: '+673', flag: '🇧🇳' },
  BG: { name: 'Bulgaria', code: 'BG', phone_code: '+359', flag: '🇧🇬' },
  BF: { name: 'Burkina Faso', code: 'BF', phone_code: '+226', flag: '🇧🇫' },
  BI: { name: 'Burundi', code: 'BI', phone_code: '+257', flag: '🇧🇮' },
  KH: { name: 'Cambodia', code: 'KH', phone_code: '+855', flag: '🇰🇭' },
  CM: { name: 'Cameroon', code: 'CM', phone_code: '+237', flag: '🇨🇲' },
  CA: { name: 'Canada', code: 'CA', phone_code: '+1', flag: '🇨🇦' },
  CV: { name: 'Cape Verde', code: 'CV', phone_code: '+238', flag: '🇨🇻' },
  KY: { name: 'Cayman Islands', code: 'KY', phone_code: '+1-345', flag: '🇰🇾' },
  CF: {
    name: 'Central African Republic',
    code: 'CF',
    phone_code: '+236',
    flag: '🇨🇫',
  },
  TD: { name: 'Chad', code: 'TD', phone_code: '+235', flag: '🇹🇩' },
  CL: { name: 'Chile', code: 'CL', phone_code: '+56', flag: '🇨🇱' },
  CN: { name: 'China', code: 'CN', phone_code: '+86', flag: '🇨🇳' },
  CX: { name: 'Christmas Island', code: 'CX', phone_code: '+61', flag: '🇨🇽' },
  CC: { name: 'Cocos Islands', code: 'CC', phone_code: '+61', flag: '🇨🇨' },
  CO: { name: 'Colombia', code: 'CO', phone_code: '+57', flag: '🇨🇴' },
  KM: { name: 'Comoros', code: 'KM', phone_code: '+269', flag: '🇰🇲' },
  CK: { name: 'Cook Islands', code: 'CK', phone_code: '+682', flag: '🇨🇰' },
  CR: { name: 'Costa Rica', code: 'CR', phone_code: '+506', flag: '🇨🇷' },
  HR: { name: 'Croatia', code: 'HR', phone_code: '+385', flag: '🇭🇷' },
  CU: { name: 'Cuba', code: 'CU', phone_code: '+53', flag: '🇨🇺' },
  CW: { name: 'Curacao', code: 'CW', phone_code: '+599', flag: '🇨🇼' },
  CY: { name: 'Cyprus', code: 'CY', phone_code: '+357', flag: '🇨🇾' },
  CZ: { name: 'Czech Republic', code: 'CZ', phone_code: '+420', flag: '🇨🇿' },
  CD: {
    name: 'Democratic Republic of the Congo',
    code: 'CD',
    phone_code: '+243',
    flag: '🇨🇩',
  },
  DK: { name: 'Denmark', code: 'DK', phone_code: '+45', flag: '🇩🇰' },
  DJ: { name: 'Djibouti', code: 'DJ', phone_code: '+253', flag: '🇩🇯' },
  DM: { name: 'Dominica', code: 'DM', phone_code: '+1-767', flag: '🇩🇲' },
  DO: {
    name: 'Dominican Republic',
    code: 'DO',
    phone_code: '+1-809',
    flag: '🇩🇴',
  },
  TL: { name: 'East Timor', code: 'TL', phone_code: '+670', flag: '🇹🇱' },
  EC: { name: 'Ecuador', code: 'EC', phone_code: '+593', flag: '🇪🇨' },
  EG: { name: 'Egypt', code: 'EG', phone_code: '+20', flag: '🇪🇬' },
  SV: { name: 'El Salvador', code: 'SV', phone_code: '+503', flag: '🇸🇻' },
  GQ: { name: 'Equatorial Guinea', code: 'GQ', phone_code: '+240', flag: '🇬🇶' },
  ER: { name: 'Eritrea', code: 'ER', phone_code: '+291', flag: '🇪🇷' },
  EE: { name: 'Estonia', code: 'EE', phone_code: '+372', flag: '🇪🇪' },
  ET: { name: 'Ethiopia', code: 'ET', phone_code: '+251', flag: '🇪🇹' },
  FK: { name: 'Falkland Islands', code: 'FK', phone_code: '+500', flag: '🇫🇰' },
  FO: { name: 'Faroe Islands', code: 'FO', phone_code: '+298', flag: '🇫🇴' },
  FJ: { name: 'Fiji', code: 'FJ', phone_code: '+679', flag: '🇫🇯' },
  FI: { name: 'Finland', code: 'FI', phone_code: '+358', flag: '🇫🇮' },
  FR: { name: 'France', code: 'FR', phone_code: '+33', flag: '🇫🇷' },
  PF: { name: 'French Polynesia', code: 'PF', phone_code: '+689', flag: '🇵🇫' },
  GA: { name: 'Gabon', code: 'GA', phone_code: '+241', flag: '🇬🇦' },
  GM: { name: 'Gambia', code: 'GM', phone_code: '+220', flag: '🇬🇲' },
  GE: { name: 'Georgia', code: 'GE', phone_code: '+995', flag: '🇬🇪' },
  DE: { name: 'Germany', code: 'DE', phone_code: '+49', flag: '🇩🇪' },
  GH: { name: 'Ghana', code: 'GH', phone_code: '+233', flag: '🇬🇭' },
  GI: { name: 'Gibraltar', code: 'GI', phone_code: '+350', flag: '🇬🇮' },
  GR: { name: 'Greece', code: 'GR', phone_code: '+30', flag: '🇬🇷' },
  GL: { name: 'Greenland', code: 'GL', phone_code: '+299', flag: '🇬🇱' },
  GD: { name: 'Grenada', code: 'GD', phone_code: '+1-473', flag: '🇬🇩' },
  GU: { name: 'Guam', code: 'GU', phone_code: '+1-671', flag: '🇬🇺' },
  GT: { name: 'Guatemala', code: 'GT', phone_code: '+502', flag: '🇬🇹' },
  GG: { name: 'Guernsey', code: 'GG', phone_code: '+44-1481', flag: '🇬🇬' },
  GN: { name: 'Guinea', code: 'GN', phone_code: '+224', flag: '🇬🇳' },
  GW: { name: 'Guinea-Bissau', code: 'GW', phone_code: '+245', flag: '🇬🇼' },
  GY: { name: 'Guyana', code: 'GY', phone_code: '+592', flag: '🇬🇾' },
  HT: { name: 'Haiti', code: 'HT', phone_code: '+509', flag: '🇭🇹' },
  HN: { name: 'Honduras', code: 'HN', phone_code: '+504', flag: '🇭🇳' },
  HK: { name: 'Hong Kong', code: 'HK', phone_code: '+852', flag: '🇭🇰' },
  HU: { name: 'Hungary', code: 'HU', phone_code: '+36', flag: '🇭🇺' },
  IS: { name: 'Iceland', code: 'IS', phone_code: '+354', flag: '🇮🇸' },
  IN: { name: 'India', code: 'IN', phone_code: '+91', flag: '🇮🇳' },
  ID: { name: 'Indonesia', code: 'ID', phone_code: '+62', flag: '🇮🇩' },
  IR: { name: 'Iran', code: 'IR', phone_code: '+98', flag: '🇮🇷' },
  IQ: { name: 'Iraq', code: 'IQ', phone_code: '+964', flag: '🇮🇶' },
  IE: { name: 'Ireland', code: 'IE', phone_code: '+353', flag: '🇮🇪' },
  IM: { name: 'Isle of Man', code: 'IM', phone_code: '+44-1624', flag: '🇮🇲' },
  IL: { name: 'Israel', code: 'IL', phone_code: '+972', flag: '🇮🇱' },
  IT: { name: 'Italy', code: 'IT', phone_code: '+39', flag: '🇮🇹' },
  CI: { name: 'Ivory Coast', code: 'CI', phone_code: '+225', flag: '🇨🇮' },
  JM: { name: 'Jamaica', code: 'JM', phone_code: '+1-876', flag: '🇯🇲' },
  JP: { name: 'Japan', code: 'JP', phone_code: '+81', flag: '🇯🇵' },
  JE: { name: 'Jersey', code: 'JE', phone_code: '+44-1534', flag: '🇯🇪' },
  JO: { name: 'Jordan', code: 'JO', phone_code: '+962', flag: '🇯🇴' },
  KZ: { name: 'Kazakhstan', code: 'KZ', phone_code: '+7', flag: '🇰🇿' },
  KE: { name: 'Kenya', code: 'KE', phone_code: '+254', flag: '🇰🇪' },
  KI: { name: 'Kiribati', code: 'KI', phone_code: '+686', flag: '🇰🇮' },
  XK: { name: 'Kosovo', code: 'XK', phone_code: '+383', flag: '🇽🇰' },
  KW: { name: 'Kuwait', code: 'KW', phone_code: '+965', flag: '🇰🇼' },
  KG: { name: 'Kyrgyzstan', code: 'KG', phone_code: '+996', flag: '🇰🇬' },
  LA: { name: 'Laos', code: 'LA', phone_code: '+856', flag: '🇱🇦' },
  LV: { name: 'Latvia', code: 'LV', phone_code: '+371', flag: '🇱🇻' },
  LB: { name: 'Lebanon', code: 'LB', phone_code: '+961', flag: '🇱🇧' },
  LS: { name: 'Lesotho', code: 'LS', phone_code: '+266', flag: '🇱🇸' },
  LR: { name: 'Liberia', code: 'LR', phone_code: '+231', flag: '🇱🇷' },
  LY: { name: 'Libya', code: 'LY', phone_code: '+218', flag: '🇱🇾' },
  LI: { name: 'Liechtenstein', code: 'LI', phone_code: '+423', flag: '🇱🇮' },
  LT: { name: 'Lithuania', code: 'LT', phone_code: '+370', flag: '🇱🇹' },
  LU: { name: 'Luxembourg', code: 'LU', phone_code: '+352', flag: '🇱🇺' },
  MO: { name: 'Macao', code: 'MO', phone_code: '+853', flag: '🇲🇴' },
  MK: { name: 'Macedonia', code: 'MK', phone_code: '+389', flag: '🇲🇰' },
  MG: { name: 'Madagascar', code: 'MG', phone_code: '+261', flag: '🇲🇬' },
  MW: { name: 'Malawi', code: 'MW', phone_code: '+265', flag: '🇲🇼' },
  MY: { name: 'Malaysia', code: 'MY', phone_code: '+60', flag: '🇲🇾' },
  MV: { name: 'Maldives', code: 'MV', phone_code: '+960', flag: '🇲🇻' },
  ML: { name: 'Mali', code: 'ML', phone_code: '+223', flag: '🇲🇱' },
  MT: { name: 'Malta', code: 'MT', phone_code: '+356', flag: '🇲🇹' },
  MH: { name: 'Marshall Islands', code: 'MH', phone_code: '+692', flag: '🇲🇭' },
  MR: { name: 'Mauritania', code: 'MR', phone_code: '+222', flag: '🇲🇷' },
  MU: { name: 'Mauritius', code: 'MU', phone_code: '+230', flag: '🇲🇺' },
  YT: { name: 'Mayotte', code: 'YT', phone_code: '+262', flag: '🇾🇹' },
  MX: { name: 'Mexico', code: 'MX', phone_code: '+52', flag: '🇲🇽' },
  FM: { name: 'Micronesia', code: 'FM', phone_code: '+691', flag: '🇫🇲' },
  MD: { name: 'Moldova', code: 'MD', phone_code: '+373', flag: '🇲🇩' },
  MC: { name: 'Monaco', code: 'MC', phone_code: '+377', flag: '🇲🇨' },
  MN: { name: 'Mongolia', code: 'MN', phone_code: '+976', flag: '🇲🇳' },
  ME: { name: 'Montenegro', code: 'ME', phone_code: '+382', flag: '🇲🇪' },
  MS: { name: 'Montserrat', code: 'MS', phone_code: '+1-664', flag: '🇲🇸' },
  MA: { name: 'Morocco', code: 'MA', phone_code: '+212', flag: '🇲🇦' },
  MZ: { name: 'Mozambique', code: 'MZ', phone_code: '+258', flag: '🇲🇿' },
  MM: { name: 'Myanmar', code: 'MM', phone_code: '+95', flag: '🇲🇲' },
  NA: { name: 'Namibia', code: 'NA', phone_code: '+264', flag: '🇳🇦' },
  NR: { name: 'Nauru', code: 'NR', phone_code: '+674', flag: '🇳🇷' },
  NP: { name: 'Nepal', code: 'NP', phone_code: '+977', flag: '🇳🇵' },
  NL: { name: 'Netherlands', code: 'NL', phone_code: '+31', flag: '🇳🇱' },
  NC: { name: 'New Caledonia', code: 'NC', phone_code: '+687', flag: '🇳🇨' },
  NZ: { name: 'New Zealand', code: 'NZ', phone_code: '+64', flag: '🇳🇿' },
  NI: { name: 'Nicaragua', code: 'NI', phone_code: '+505', flag: '🇳🇮' },
  NE: { name: 'Niger', code: 'NE', phone_code: '+227', flag: '🇳🇪' },
  NG: { name: 'Nigeria', code: 'NG', phone_code: '+234', flag: '🇳🇬' },
  NU: { name: 'Niue', code: 'NU', phone_code: '+683', flag: '🇳🇺' },
  KP: { name: 'North Korea', code: 'KP', phone_code: '+850', flag: '🇰🇵' },
  MP: {
    name: 'Northern Mariana Islands',
    code: 'MP',
    phone_code: '+1-670',
    flag: '🇲🇵',
  },
  NO: { name: 'Norway', code: 'NO', phone_code: '+47', flag: '🇳🇴' },
  OM: { name: 'Oman', code: 'OM', phone_code: '+968', flag: '🇴🇲' },
  PK: { name: 'Pakistan', code: 'PK', phone_code: '+92', flag: '🇵🇰' },
  PW: { name: 'Palau', code: 'PW', phone_code: '+680', flag: '🇵🇼' },
  PS: { name: 'Palestine', code: 'PS', phone_code: '+970', flag: '🇵🇸' },
  PA: { name: 'Panama', code: 'PA', phone_code: '+507', flag: '🇵🇦' },
  PG: { name: 'Papua New Guinea', code: 'PG', phone_code: '+675', flag: '🇵🇬' },
  PY: { name: 'Paraguay', code: 'PY', phone_code: '+595', flag: '🇵🇾' },
  PE: { name: 'Peru', code: 'PE', phone_code: '+51', flag: '🇵🇪' },
  PH: { name: 'Philippines', code: 'PH', phone_code: '+63', flag: '🇵🇭' },
  PL: { name: 'Poland', code: 'PL', phone_code: '+48', flag: '🇵🇱' },
  PT: { name: 'Portugal', code: 'PT', phone_code: '+351', flag: '🇵🇹' },
  PR: { name: 'Puerto Rico', code: 'PR', phone_code: '+1-787', flag: '🇵🇷' },
  QA: { name: 'Qatar', code: 'QA', phone_code: '+974', flag: '🇶🇦' },
  CG: {
    name: 'Republic of the Congo',
    code: 'CG',
    phone_code: '+242',
    flag: '🇨🇬',
  },
  RE: { name: 'Reunion', code: 'RE', phone_code: '+262', flag: '🇷🇪' },
  RO: { name: 'Romania', code: 'RO', phone_code: '+40', flag: '🇷🇴' },
  RU: { name: 'Russia', code: 'RU', phone_code: '+7', flag: '🇷🇺' },
  RW: { name: 'Rwanda', code: 'RW', phone_code: '+250', flag: '🇷🇼' },
  BL: { name: 'Saint Barthelemy', code: 'BL', phone_code: '+590', flag: '🇧🇱' },
  SH: { name: 'Saint Helena', code: 'SH', phone_code: '+290', flag: '🇸🇭' },
  KN: {
    name: 'Saint Kitts and Nevis',
    code: 'KN',
    phone_code: '+1-869',
    flag: '🇰🇳',
  },
  LC: { name: 'Saint Lucia', code: 'LC', phone_code: '+1-758', flag: '🇱🇨' },
  MF: { name: 'Saint Martin', code: 'MF', phone_code: '+590', flag: '🇲🇫' },
  PM: {
    name: 'Saint Pierre and Miquelon',
    code: 'PM',
    phone_code: '+508',
    flag: '🇵🇲',
  },
  VC: {
    name: 'Saint Vincent and the Grenadines',
    code: 'VC',
    phone_code: '+1-784',
    flag: '🇻🇨',
  },
  WS: { name: 'Samoa', code: 'WS', phone_code: '+685', flag: '🇼🇸' },
  SM: { name: 'San Marino', code: 'SM', phone_code: '+378', flag: '🇸🇲' },
  ST: {
    name: 'Sao Tome and Principe',
    code: 'ST',
    phone_code: '+239',
    flag: '🇸🇹',
  },
  SA: { name: 'Saudi Arabia', code: 'SA', phone_code: '+966', flag: '🇸🇦' },
  SN: { name: 'Senegal', code: 'SN', phone_code: '+221', flag: '🇸🇳' },
  RS: { name: 'Serbia', code: 'RS', phone_code: '+381', flag: '🇷🇸' },
  SC: { name: 'Seychelles', code: 'SC', phone_code: '+248', flag: '🇸🇨' },
  SL: { name: 'Sierra Leone', code: 'SL', phone_code: '+232', flag: '🇸🇱' },
  SG: { name: 'Singapore', code: 'SG', phone_code: '+65', flag: '🇸🇬' },
  SX: { name: 'Sint Maarten', code: 'SX', phone_code: '+1-721', flag: '🇸🇽' },
  SK: { name: 'Slovakia', code: 'SK', phone_code: '+421', flag: '🇸🇰' },
  SI: { name: 'Slovenia', code: 'SI', phone_code: '+386', flag: '🇸🇮' },
  SB: { name: 'Solomon Islands', code: 'SB', phone_code: '+677', flag: '🇸🇧' },
  SO: { name: 'Somalia', code: 'SO', phone_code: '+252', flag: '🇸🇴' },
  ZA: { name: 'South Africa', code: 'ZA', phone_code: '+27', flag: '🇿🇦' },
  KR: { name: 'South Korea', code: 'KR', phone_code: '+82', flag: '🇰🇷' },
  SS: { name: 'South Sudan', code: 'SS', phone_code: '+211', flag: '🇸🇸' },
  ES: { name: 'Spain', code: 'ES', phone_code: '+34', flag: '🇪🇸' },
  LK: { name: 'Sri Lanka', code: 'LK', phone_code: '+94', flag: '🇱🇰' },
  SD: { name: 'Sudan', code: 'SD', phone_code: '+249', flag: '🇸🇩' },
  SR: { name: 'Suriname', code: 'SR', phone_code: '+597', flag: '🇸🇷' },
  SJ: {
    name: 'Svalbard and Jan Mayen',
    code: 'SJ',
    phone_code: '+47',
    flag: '🇸🇯',
  },
  SZ: { name: 'Swaziland', code: 'SZ', phone_code: '+268', flag: '🇸🇿' },
  SE: { name: 'Sweden', code: 'SE', phone_code: '+46', flag: '🇸🇪' },
  CH: { name: 'Switzerland', code: 'CH', phone_code: '+41', flag: '🇨🇭' },
  SY: { name: 'Syria', code: 'SY', phone_code: '+963', flag: '🇸🇾' },
  TW: { name: 'Taiwan', code: 'TW', phone_code: '+886', flag: '🇹🇼' },
  TJ: { name: 'Tajikistan', code: 'TJ', phone_code: '+992', flag: '🇹🇯' },
  TZ: { name: 'Tanzania', code: 'TZ', phone_code: '+255', flag: '🇹🇿' },
  TH: { name: 'Thailand', code: 'TH', phone_code: '+66', flag: '🇹🇭' },
  TG: { name: 'Togo', code: 'TG', phone_code: '+228', flag: '🇹🇬' },
  TK: { name: 'Tokelau', code: 'TK', phone_code: '+690', flag: '🇹🇰' },
  TO: { name: 'Tonga', code: 'TO', phone_code: '+676', flag: '🇹🇴' },
  TT: {
    name: 'Trinidad and Tobago',
    code: 'TT',
    phone_code: '+1-868',
    flag: '🇹🇹',
  },
  TN: { name: 'Tunisia', code: 'TN', phone_code: '+216', flag: '🇹🇳' },
  TR: { name: 'Turkey', code: 'TR', phone_code: '+90', flag: '🇹🇷' },
  TM: { name: 'Turkmenistan', code: 'TM', phone_code: '+993', flag: '🇹🇲' },
  TC: {
    name: 'Turks and Caicos Islands',
    code: 'TC',
    phone_code: '+1-649',
    flag: '🇹🇨',
  },
  TV: { name: 'Tuvalu', code: 'TV', phone_code: '+688', flag: '🇹🇻' },
  VI: {
    name: 'U.S. Virgin Islands',
    code: 'VI',
    phone_code: '+1-340',
    flag: '🇻🇮',
  },
  UG: { name: 'Uganda', code: 'UG', phone_code: '+256', flag: '🇺🇬' },
  UA: { name: 'Ukraine', code: 'UA', phone_code: '+380', flag: '🇺🇦' },
  AE: {
    name: 'United Arab Emirates',
    code: 'AE',
    phone_code: '+971',
    flag: '🇦🇪',
  },
  GB: { name: 'United Kingdom', code: 'GB', phone_code: '+44', flag: '🇬🇧' },
  US: { name: 'United States', code: 'US', phone_code: '+1', flag: '🇺🇸' },
  UY: { name: 'Uruguay', code: 'UY', phone_code: '+598', flag: '🇺🇾' },
  UZ: { name: 'Uzbekistan', code: 'UZ', phone_code: '+998', flag: '🇺🇿' },
  VU: { name: 'Vanuatu', code: 'VU', phone_code: '+678', flag: '🇻🇺' },
  VA: { name: 'Vatican', code: 'VA', phone_code: '+379', flag: '🇻🇦' },
  VE: { name: 'Venezuela', code: 'VE', phone_code: '+58', flag: '🇻🇪' },
  VN: { name: 'Vietnam', code: 'VN', phone_code: '+84', flag: '🇻🇳' },
  WF: { name: 'Wallis and Futuna', code: 'WF', phone_code: '+681', flag: '🇼🇫' },
  EH: { name: 'Western Sahara', code: 'EH', phone_code: '+212', flag: '🇪🇭' },
  YE: { name: 'Yemen', code: 'YE', phone_code: '+967', flag: '🇾🇪' },
  ZM: { name: 'Zambia', code: 'ZM', phone_code: '+260', flag: '🇿🇲' },
  ZW: { name: 'Zimbabwe', code: 'ZW', phone_code: '+263', flag: '🇿🇼' },
  GLOBAL: { name: 'Global', code: 'GLOBAL', phone_code: '', flag: '🌐' },
};

export const getPhoneCode = (countryCode: string): string => {
  return COUNTRIES[countryCode]?.phone_code || '';
};
