/** @format */

import 'dotenv/config';
import { createClient } from '@supabase/supabase-js';
import { readFileSync } from 'fs';
import path from 'path';

// Load env
const envPath = path.resolve(process.cwd(), '.env.local');
try {
  const envConfig = readFileSync(envPath, 'utf8');
  envConfig.split('\n').forEach((line) => {
    const [key, value] = line.split('=');
    if (key && value) {
      process.env[key.trim()] = value.trim();
    }
  });
} catch (e) {
  console.log('Could not read .env.local');
}

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl || !supabaseKey) {
  console.error('Missing Supabase credentials');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

async function run() {
  console.log('--- Creating Mock Shipment ---');

  // 1. Get a Tenant (Prefer India)
  const { data: tenants, error: tenantError } = await supabase
    .from('tenants')
    .select('id, name, code')
    .ilike('name', '%india%')
    .limit(1);

  let tenantId;
  if (tenants && tenants.length > 0) {
    tenantId = tenants[0].id;
    console.log(`Using Tenant: ${tenants[0].name} (${tenantId})`);
  } else {
    // Fallback to any tenant
    const { data: anyTenant } = await supabase
      .from('tenants')
      .select('id')
      .limit(1)
      .single();
    if (!anyTenant) {
      console.error('No tenants found in DB. Cannot create shipment.');
      return;
    }
    tenantId = anyTenant.id;
    console.log(`Using Fallback Tenant ID: ${tenantId}`);
  }

  // 1.5 Get a Carrier
  let { data: carriers } = await supabase
    .from('carriers')
    .select('id, code')
    .limit(1);
  let carrierId;
  let carrierCode;

  if (!carriers || carriers.length === 0) {
    console.log('No carriers found. Creating a mock carrier...');
    const { data: newCarrier, error: carrierError } = await supabase
      .from('carriers')
      .insert({
        code: 'mock_carrier',
      })
      .select()
      .single();

    if (carrierError) {
      console.error('Failed to create mock carrier:', carrierError.message);
      return;
    }
    carrierId = newCarrier.id;
    carrierCode = newCarrier.code;
  } else {
    carrierId = carriers[0].id;
    carrierCode = carriers[0].code;
  }

  console.log(`Using Carrier: ${carrierCode} (${carrierId})`);

  // 2. Generate Mock Data
  const trackingNumber = `MOCK-${Math.floor(Math.random() * 1000000)}`;
  const mockShipment = {
    tenant_id: tenantId,
    carrier_id: carrierId, // Use dynamic carrier ID
    carrier_tracking_code: trackingNumber,
    white_label_code: `WL-${Math.floor(Math.random() * 1000)}`,
    provider: carrierCode,
    status: 'pending',
    origin_country: 'IN',
    destination_country: 'US',
    customer_details: {
      name: 'Test User',
      email: 'test@example.com',
      phone: '+919999999999',
    },
    invoice_details: {
      amount: 1500,
      currency: 'INR',
    },
    raw_response: {
      mock: true,
      note: 'Generated by seed script',
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  };

  // 3. Insert Shipment
  const { data, error } = await supabase
    .from('shipments')
    .insert(mockShipment)
    .select()
    .single();

  if (error) {
    console.error('Error creating shipment:', error.message);
  } else {
    console.log('✅ Shipment Created Successfully!');
    console.log(`ID: ${data.id}`);
    console.log(`Tracking Code: ${data.carrier_tracking_code}`);
    console.log(`Status: ${data.status}`);
    console.log(`Customer Email: ${data.customer_details.email}`);
    console.log('\nYou can now test notifications for this shipment.');
  }
}

run();
